default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("RAILS_DATABASE_HOST") { 'postgres' } %>
  username: <%= ENV.fetch("RAILS_DATABASE_USER") { 'postgres' } %>
  password: <%= ENV.fetch("RAILS_DATABASE_PASSWORD") { 'password' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { 'myapp_test' } %>

production:
  <<: *default
  database: myapp_production
